/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Datos.TextTographics;
import Datos.TextTographics;
import Negocio.Logica;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

/**
 *
 * @author lucas
 */
public class Presentacion1 extends javax.swing.JFrame {

    
String currentcaptcha;
    /**
     * Creates new form GaySiElQueLoLea
     */
    public Presentacion1() {
        initComponents();
        lblimg.setText("");
        reset();
                ladoD01.setSize(540, 810);
                ladoD01.setLocation(0, 0);
                content02.removeAll();
                content02.add(ladoD01, BorderLayout.CENTER);
                content02.revalidate();
                content02.repaint();
        ladoI01.setSize(540,810);
        ladoI01.setLocation(0,0);
        content01.removeAll();
                content01.add(ladoI01, BorderLayout.CENTER);
                content01.revalidate();
                content01.repaint();
                
    }
    public void reset(){
        try {
            currentcaptcha=TextTographics.generateImage();
            Image img=ImageIO.read(new File("C:\\Users\\51935\\Desktop\\ArquitecturaSoftware003\\ArquitecturaSoftware003\\text.png"));
            lblimg.setIcon(new ImageIcon(img));
        } catch (IOException ex) {
        }
    }
boolean Verificacion=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ladoD01 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNacimiento = new javax.swing.JTextField();
        lblEmision = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtEmision = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();
        captchapuesto = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        ladoI01 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ladoD02 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        ladoI02 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        CarnetCovid = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        lblNumeroDosis = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        Check2 = new javax.swing.JCheckBox();
        Check1 = new javax.swing.JCheckBox();
        Check4 = new javax.swing.JCheckBox();
        Check3 = new javax.swing.JCheckBox();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        content02 = new javax.swing.JPanel();
        content01 = new javax.swing.JPanel();

        ladoD01.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Identifica para ingresar");

        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI - Documento Nacional de Identidad", "CE - Carnét de extranjeria", "Pasaporte", "Documento de Identidad Extranjero", "Código Temporal de Acceso", "Permiso Temporal de Permanencia" }));
        cbTipoDocumento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoDocumentoItemStateChanged(evt);
            }
        });

        jLabel3.setText("Número de Documento");

        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        jLabel4.setText("Fecha de Nacimiento");

        txtNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyTyped(evt);
            }
        });

        lblEmision.setText("Fecha de Emision de tu DNI");

        jCheckBox1.setText("Mantener mi sesión iniciada por 07 dias.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Revisa la Politica de Privacidad de Terminos y Condiciones de la Plataforma");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Selecciona tu tipo de Documento");

        txtEmision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmisionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmisionKeyTyped(evt);
            }
        });

        lblimg.setText("jLabel5");

        captchapuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captchapuestoActionPerformed(evt);
            }
        });

        jButton6.setText("Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ladoD01Layout = new javax.swing.GroupLayout(ladoD01);
        ladoD01.setLayout(ladoD01Layout);
        ladoD01Layout.setHorizontalGroup(
            ladoD01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoD01Layout.createSequentialGroup()
                .addGroup(ladoD01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoD01Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(ladoD01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(ladoD01Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))))
                    .addGroup(ladoD01Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1))
                    .addGroup(ladoD01Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(ladoD01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(captchapuesto, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jCheckBox1)
                            .addComponent(lblEmision)
                            .addComponent(txtNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(cbTipoDocumento, javax.swing.GroupLayout.Alignment.TRAILING, 0, 332, Short.MAX_VALUE)
                            .addComponent(txtEmision, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                            .addComponent(lblimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        ladoD01Layout.setVerticalGroup(
            ladoD01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoD01Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblEmision)
                .addGap(18, 18, 18)
                .addComponent(txtEmision, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ladoD01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimg, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(24, 24, 24)
                .addComponent(captchapuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotipo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Te damos la bienvenida a Carné de Vacunación");

        jLabel10.setText("En esta plataforma podrás:");

        jLabel11.setText("Ver y descargar tu Carné de Vacunación.");

        jLabel12.setText("Verificar la validez de un código QR.");

        jLabel13.setText("Ver el detalle de tu esquema de vacunación.");

        jLabel14.setText("Descargar tu certificado de vacunación.");

        jLabel15.setText("Solicitar el registro de tu vacunación COVID-19.");

        javax.swing.GroupLayout ladoI01Layout = new javax.swing.GroupLayout(ladoI01);
        ladoI01.setLayout(ladoI01Layout);
        ladoI01Layout.setHorizontalGroup(
            ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI01Layout.createSequentialGroup()
                .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoI01Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel8))
                    .addGroup(ladoI01Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addGroup(ladoI01Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9))
                    .addGroup(ladoI01Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        ladoI01Layout.setVerticalGroup(
            ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI01Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addGap(74, 74, 74)
                .addComponent(jLabel10)
                .addGap(38, 38, 38)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        ladoD02.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ingresar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Ingresa al Carné de Vacunacion de ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("menores de edad");

        jLabel18.setText("Debes ser progenitor o apoderado del menor");

        jLabel19.setText("para realizar esta consulta.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jButton4.setText("Carné de Vacunación COVID-19");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ladoD02Layout = new javax.swing.GroupLayout(ladoD02);
        ladoD02.setLayout(ladoD02Layout);
        ladoD02Layout.setHorizontalGroup(
            ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoD02Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        ladoD02Layout.setVerticalGroup(
            ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoD02Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotipo.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Bienvenido a tu Carné de Vacunación");

        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nLos mayores de 5 años podrán ver su historial de vacunación del 2022 \nen adelante y los menores de 5 años desde el 2019 en adelante. Si tu \nvacunación no se encuentra registrada puedes mostrar tu carné físico.");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel22.setText("Elige que Carné de Vacunación quieres mostrar.");

        jLabel23.setText("Haz clic en cada uno para más detalle.");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("\nSi tienes alguna observación sobre la información del Carné\nVirtual acude al establecimiento de salud donde se realizó la\nvacunación para la evaluación del caso.");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout ladoI02Layout = new javax.swing.GroupLayout(ladoI02);
        ladoI02.setLayout(ladoI02Layout);
        ladoI02Layout.setHorizontalGroup(
            ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI02Layout.createSequentialGroup()
                .addGroup(ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoI02Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel20))
                    .addGroup(ladoI02Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        ladoI02Layout.setVerticalGroup(
            ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI02Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel20)
                .addGap(37, 37, 37)
                .addComponent(jLabel21)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jButton5.setText("<- Volver");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setBackground(new java.awt.Color(255, 255, 0));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/qr.png"))); // NOI18N
        jLabel24.setOpaque(true);

        lblNombre.setText("Nombre");

        lblDni.setText("DNI:");

        lblEdad.setText("Edad");

        jSeparator1.setForeground(new java.awt.Color(51, 255, 0));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 255));
        jLabel27.setText("VACUNACIÓN COVID-19");

        lblNumeroDosis.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNumeroDosis.setForeground(new java.awt.Color(0, 204, 0));
        lblNumeroDosis.setText("NUMERO DE DOSIS");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Dosis");

        Check2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check2.setOpaque(true);

        Check1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check1.setOpaque(true);

        Check4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check4.setOpaque(true);

        Check3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check3.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(45, 45, 45)
                .addComponent(Check1)
                .addGap(18, 18, 18)
                .addComponent(Check2)
                .addGap(18, 18, 18)
                .addComponent(Check3)
                .addGap(18, 18, 18)
                .addComponent(Check4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Check4)
                    .addComponent(Check2)
                    .addComponent(Check1)
                    .addComponent(Check3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEdad))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))))
                .addGap(70, 70, 70))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumeroDosis)
                            .addComponent(jLabel27))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombre)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroDosis)
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CarnetCovidLayout = new javax.swing.GroupLayout(CarnetCovid);
        CarnetCovid.setLayout(CarnetCovidLayout);
        CarnetCovidLayout.setHorizontalGroup(
            CarnetCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarnetCovidLayout.createSequentialGroup()
                .addGroup(CarnetCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarnetCovidLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton5))
                    .addGroup(CarnetCovidLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        CarnetCovidLayout.setVerticalGroup(
            CarnetCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarnetCovidLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(803, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        content02.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout content02Layout = new javax.swing.GroupLayout(content02);
        content02.setLayout(content02Layout);
        content02Layout.setHorizontalGroup(
            content02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        content02Layout.setVerticalGroup(
            content02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        getContentPane().add(content02, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 540, 810));

        content01.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout content01Layout = new javax.swing.GroupLayout(content01);
        content01.setLayout(content01Layout);
        content01Layout.setHorizontalGroup(
            content01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        content01Layout.setVerticalGroup(
            content01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        getContentPane().add(content01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2MouseClicked
int numeroDocumento;
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Logica logica =new Logica();
        camposVacios();
        numeroDocumento=Integer.parseInt(txtDocumento.getText());
        if(!logica.validarExistencia(numeroDocumento, txtNacimiento.getText(), txtEmision.getText())){
            Verificacion=false;
        }

        // TODO add your handling code here:
        
if(Verificacion&&captchapuesto.getText().equals(currentcaptcha)){
    numeroDocumento=Integer.parseInt(txtDocumento.getText());
    ladoD02.setSize(540, 810);
                ladoD02.setLocation(0, 0);
                content02.removeAll();
                content02.add(ladoD02, BorderLayout.CENTER);
                content02.revalidate();
                content02.repaint();
        ladoI02.setSize(540, 810);
                ladoI02.setLocation(0, 0);
                content01.removeAll();
                content01.add(ladoI02, BorderLayout.CENTER);
                content01.revalidate();
                content01.repaint();

}else{
    
    if (!captchapuesto.getText().equals(currentcaptcha)){
            JOptionPane.showMessageDialog(null, "Captcha fallido");}
    else{
        JOptionPane.showMessageDialog(null, "Verifique los datos");
    }
           
        }    
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        CarnetCovid.setSize(540, 810);
                CarnetCovid.setLocation(0, 0);
                content01.removeAll();
                content01.add(CarnetCovid, BorderLayout.CENTER);
                content01.revalidate();
                content01.repaint();
                obtenerDatos();
    }//GEN-LAST:event_jButton4MouseClicked

    private void cbTipoDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoDocumentoItemStateChanged
        // TODO add your handling code here:
        switch (cbTipoDocumento.getSelectedIndex()) {
            case 0 -> {
                lblEmision.setVisible(true);
                txtEmision.setVisible(true);
            }
            case 1, 2, 3, 4, 5 -> {
                lblEmision.setVisible(false);
                txtEmision.setVisible(false);
            }
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_cbTipoDocumentoItemStateChanged

    private void txtNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '/') {
                evt.consume(); // Ignora el evento si no es un número o '/'
            }
            if(txtNacimiento.getText().length()>=10){
                evt.consume();
            }
    }//GEN-LAST:event_txtNacimientoKeyTyped

    private void txtNacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyReleased
        // TODO add your handling code here:
        if ((txtNacimiento.getText().length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)||(txtNacimiento.getText().length() == 5 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
                    txtNacimiento.setText(txtNacimiento.getText() + "/");
                }
        if(esFechaValida(txtNacimiento.getText())){
            txtNacimiento.setForeground(Color.black);
        }else{
            txtNacimiento.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtNacimientoKeyReleased

    private void txtEmisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmisionKeyReleased
        // TODO add your handling code here:
        if ((txtEmision.getText().length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)||(txtEmision.getText().length() == 5 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
                    txtEmision.setText(txtEmision.getText() + "/");
                }
        if(esFechaValida(txtEmision.getText())){
            txtEmision.setForeground(Color.black);
        }else{
            txtEmision.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtEmisionKeyReleased

    private void txtEmisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmisionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
            if (!Character.isDigit(c) && c != '/') {
                evt.consume(); // Ignora el evento si no es un número o '/'
            }
            if(txtEmision.getText().length()>=10){
                evt.consume();
            }
    }//GEN-LAST:event_txtEmisionKeyTyped

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        // TODO add your handling code here:
       char c = evt.getKeyChar();
                if (!Character.isDigit(c) || txtDocumento.getText().length() >= 8) {
                    evt.consume(); // Ignorar la tecla si no es un dígito numérico o se alcanzó la longitud máxima
                }
                if( txtDocumento.getText().length()==07){
                    Verificacion=true;
                }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    
    

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void captchapuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captchapuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_captchapuestoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
reset();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
         ladoI02.setSize(540, 810);
                ladoI02.setLocation(0, 0);
                content01.removeAll();
                content01.add(ladoI02, BorderLayout.CENTER);
                content01.revalidate();
                content01.repaint();
    }//GEN-LAST:event_jButton5MouseClicked

    private boolean esFechaValida(String fecha) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // Hacer que el análisis de fecha sea estricto

        try {
            Date date = sdf.parse(fecha);
            Verificacion = true;
            return true; // La cadena es una fecha válida
        } catch (ParseException e) {
            Verificacion=false;
            return false; // La cadena no es una fecha válida
        }
    }
    private void camposVacios(){
        
        if(txtDocumento.getText().isEmpty()||txtNacimiento.getText().isEmpty()){
            Verificacion=false;
        }
        if(cbTipoDocumento.getSelectedIndex()==0){
            if(txtEmision.getText().isEmpty()){
                Verificacion=false;
            }
        }
    }
    private void obtenerDatos(){
        Logica logica = new Logica();
        lblNombre.setText(logica.obtenerNombre(numeroDocumento));
        lblDni.setText("DNI: "+numeroDocumento);
        lblEdad.setText("Edad: "+logica.obtenerEdad(numeroDocumento));
        switch (logica.obtenerNumeroDosis(numeroDocumento)) {
            case 0 -> lblNumeroDosis.setText("NINGUNA DOSIS");
            case 1 ->{ lblNumeroDosis.setText("CON PRIMERA DOSIS");
                    Check1.setSelected(true);
            }
            case 2 -> {lblNumeroDosis.setText("CON SEGUNDA DOSIS");
                    Check1.setSelected(true);
                    Check2.setSelected(true);
            }
            case 3 ->{ lblNumeroDosis.setText("CON TERCERA DOSIS");
                    Check1.setSelected(true);
                    Check2.setSelected(true);
                    Check3.setSelected(true);
                }
            case 4 -> {lblNumeroDosis.setText("CON CUARTA DOSIS");
                    Check1.setSelected(true);
                    Check2.setSelected(true);
                    Check3.setSelected(true);
                    Check4.setSelected(true);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion1().setVisible(true);
            }
        });
    }

   public void cambiarPanelIzquierdo(JPanel panel){
       
                panel.setSize(540, 810);
                panel.setLocation(0, 0);
                content02.removeAll();
                content02.add(panel, BorderLayout.CENTER);
                content02.revalidate();
                content02.repaint();
   }
   public void cambiarPanelDerecho(javax.swing.JPanel panel){
       
                panel.setSize(540, 810);
                panel.setLocation(0, 0);
                content01.removeAll();
                content01.add(panel, BorderLayout.CENTER);
                content01.revalidate();
                content01.repaint();
                panel.setVisible(true);
                
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarnetCovid;
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JCheckBox Check4;
    private javax.swing.JTextField captchapuesto;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JPanel content01;
    private javax.swing.JPanel content02;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel ladoD01;
    private javax.swing.JPanel ladoD02;
    private javax.swing.JPanel ladoI01;
    private javax.swing.JPanel ladoI02;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmision;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroDosis;
    private javax.swing.JLabel lblimg;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmision;
    private javax.swing.JTextField txtNacimiento;
    // End of variables declaration//GEN-END:variables
}
